apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ain4jusrv-nodejs 
  janus-idp.io/tekton: ain4jusrv-nodejs
  backstage.io/kubernetes-id: ain4jusrv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ain4jusrv-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  