apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ain4jusrv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ain4jusrv-nodejs 
  name: ain4jusrv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ain4jusrv-nodejs 
